dotfiles_dir = "projects/dotfiles"
gpg_user_id  = "rasmus@bertell.fi"

import = []

[settings]
vars      = []
prehooks  = []
posthooks = ["scripts/install_tpm.sh"]

[settings.dots]
gitconfig = { source = "git/config",     target = ".config/git/config" }
tmux      = { source = "tmux/tmux.conf", target = ".config/tmux/tmux.conf" }
