dotfiles_dir = "projects/dotfiles"
gpg_user_id  = "rasmus@bertell.fi"

import = []

[settings]
vars      = [ "vars/default.toml" ]
prehooks  = []
posthooks = []

[settings.dots]
gitconfig = { source = "git/config",             target = ".config/git/config" }
nvim      = { source = "nvim/init.lua",          target = ".config/nvim/init.lua" }
nvim_conf = { source = "nvim/lua",               target = ".config/nvim/lua" }
nvim_plug = { source = "nvim/plugin",            target = ".config/nvim/plugin" }
zellij    = { source = "zellij/config.kdl",      target = ".config/zellij/config.kdl" }
nushell   = { source = "nushell/config.nu",      target = ".config/nushell/config.nu" }
ghostty   = { source = "ghostty/config.ghostty", target = ".config/ghostty/config.ghostty" }
zathura   = { source = "zathura/zathurarc",      target = ".config/zathura/zathurarc" }
gpg-agent = { source = "gnupg/gpg-agent.conf",   target = ".gnupg/gpg-agent.conf" }
scdaemon  = { source = "gnupg/scdaemon.conf",    target = ".gnupg/scdaemon.conf" }

rose-pine-zathura = { source = "rose-pine/zathura",     target = ".config/zathura/themes" }
rose-pine-zellij  = { source = "rose-pine/zellij/dist", target = ".config/zellij/themes" }

[profiles.work]
vars           = [ "vars/work.toml" ]
prehooks       = []
posthooks      = []
extra_profiles = []

[profiles.work.dots]
